import difference_equations_scaling_q_differences_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace difference_equations_scaling_q_differences_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end difference_equations_scaling_q_differences_theorem_canonical_lane_mathlib
end HautevilleHouse
